### ISSUE TITLE
kdconv 榜单 distinct 指标计算

### ISSUE THREAD

**Issue by Cherryjingyao** [TsinghuaAI/CUGE#6]
我使用kdconv数据集中的baseline方法memhred模型得出的结果进行提交，最后的得分为9.17
其中BLEU : 21.08，Distinct : 3.09。distinct 2指标和论文中出入很大，请问评估是怎么计算的呢

**Comment by yaoyuanTHU** [comment]
你好，所有数据集的评测脚本均已开源，在相应数据集下载中即可获得，可以在评测代码中查看评测方法实现细节。

**Comment by noobimp** [comment]
评测代码是哪个啊，数据集里的eval.py计算出来BLEU和Distinct得分，和论文里的单个得分怎么对应的
