### ISSUE TITLE
关于 Math23K 数据集测评方法的疑问

### ISSUE THREAD

**Issue by alumik** [TsinghuaAI/CUGE#7]
既然是测试模型的数学计算能力，为何要在测试代码里直接比较答案的字符串是否相等呢？

从本人的模型输出来看，有以下情况导致模型的准确率很低：

| 我的模型输出 | （可能的）标准答案 |
| - | - |
| 1.0 | 1 |
| 0.5 | ((1)/(2)) |
| 0.333333| ((1)/(3)) |

如果直接比较字符串是否相等，三个答案会完全对不上，对模型测评不太公平。
就算是考虑到精度问题，上述表中的一二例也应判断为正确。

希望能对 Math23K 的准确度评价标准做出改进。

**Comment by yaoyuanTHU** [comment]
您好，感谢反馈建议。我们会对评测标准做出改进

**Comment by fomalhautn** [comment]
Hi. Have you created a similar architecture for English (github.com/TsinghuaAI/CUGE)? Could you please share a link? 
Thank you.

**Comment by helloxcq** [comment]
您好，我们已对Math23K的评测标准进行了优化，期待您的进一步尝试和反馈！
